application: natalie1words
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /html
  static_dir: static/html

- url: /_ah/spi/.*
  script: endpoint_apis.application

- url: /login
  script: home.application

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0

